# Generated by Django 5.1.6 on 2025-02-19 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_type', models.CharField(choices=[('basic', 'Basic')], default='basic', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='market.market')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
